CSR-2: Reactive CRUD repository
Education-platform-JMA/jmacourseservice pull request #7
Opened 2021-10-05 22:54 UTC by Tim0f3y

2021-10-06 05:53 UTC, FanilBiktimirov requested changes

2021-10-06 05:53 UTC, FanilBiktimirov commented on src/main/java/ru/jma/jmacourseservice/JmaCoursesServiceApplication.java
> +    @Primary
Need to add this annotation?

2021-10-06 05:53 UTC, FanilBiktimirov commented on src/main/java/ru/jma/jmacourseservice/JmaCoursesServiceApplication.java
> +    public ObjectMapper objectMapper() {
Create configuration class

2021-10-06 05:53 UTC, FanilBiktimirov commented on src/main/java/ru/jma/jmacourseservice/controller/CourseController.java
> +    public Flux<CourseDto> getAllCourses(@RequestParam(required = false) String name) {
What is it name?

2021-10-06 05:53 UTC, FanilBiktimirov commented on src/main/java/ru/jma/jmacourseservice/controller/CourseController.java
> +    private final ObjectMapper objectMapper;
Try to use Mapstruct

2021-10-06 05:53 UTC, FanilBiktimirov commented on src/main/java/ru/jma/jmacourseservice/service/CourseService.java
> +
Formatting

2021-10-13 05:09 UTC, ilya2236 approved these changes

2021-10-13 18:43 UTC, FanilBiktimirov approved these changes

2021-10-13 19:09 UTC, merged